/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=beta --include-runtime=false server/worker-configuration.d.ts` (hash: 988d71cf01b8cfa820ace3a47005ee1a)
interface __BaseEnv_Env {
	DB: D1Database;
	GOOGLE_CLIENT_SECRET: SecretsStoreSecret;
	GOOGLE_TOKEN_ENCRYPTION_KEY: SecretsStoreSecret;
	VAPID_PRIVATE_KEY: SecretsStoreSecret;
	RESEND_API_KEY: SecretsStoreSecret;
	ADMIN_EMAIL: SecretsStoreSecret;
	AI: Ai;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	GOOGLE_CLIENT_ID: "621931405628-lc7afq5qp0ejmdks5hl9c6b7uclskiie.apps.googleusercontent.com";
	VAPID_PUBLIC_KEY: "BHVSXcjfORTKBlCSOyokP1Iq9Jwgnuetorda-TEqjEUjvK4hZjp-PE1p4qDJ7Tgq3dywzervtXgt0VKzMxfJZG8";
	VAPID_SUBJECT: "mailto:nicolajbach12@gmail.com";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
